# Generated by Django 5.2.15 on 2026-06-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_document_expiry_date_document_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
