# Generated by Django 5.2.15 on 2026-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_passport_passport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='passport_image',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'پاسپورت'), ('visa', 'ویزا'), ('national_card', 'کارت ملی'), ('personal_photo', 'عکس پرسنلی'), ('ticket', 'بلیت'), ('insurance', 'بیمه'), ('other', 'سایر')], max_length=30),
        ),
    ]
