# Generated by Django 5.2.15 on 2026-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_remove_passport_passport_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport_image', 'تصویر پاسپورت'), ('visa', 'ویزا'), ('national_card', 'کارت ملی'), ('personal_photo', 'عکس پرسنلی'), ('ticket', 'بلیت'), ('insurance', 'بیمه'), ('other', 'سایر')], max_length=30),
        ),
    ]
