# Generated by Django 5.2.15 on 2026-09-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hotel', 'هتل'), ('airline', 'ایرلاین'), ('driver', 'راننده'), ('guide', 'راهنما'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('insurance', 'بیمه'), ('advertising', 'تبلیغات'), ('office', 'هزینه دفتر'), ('other', 'سایر')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paid_at', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('online', 'پرداخت آنلاین'), ('installment', 'اقساطی')], max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
        ),
    ]
