# Generated by Django 5.2.15 on 2026-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hotel', 'هتل'), ('airline', 'ایرلاین'), ('driver', 'راننده'), ('guide', 'راهنما'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('insurance', 'بیمه'), ('advertising', 'تبلیغات'), ('office', 'هزینه دفتر'), ('other', 'سایر')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paid_at', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
