# Generated by Django 5.2.15 on 2026-06-20 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_refund'),
        ('payments', '0003_expense_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bookings.booking'),
        ),
    ]
