# Generated by Django 5.2.15 on 2026-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تور')),
                ('tour_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='کد تور')),
                ('destination', models.CharField(max_length=100, verbose_name='مقصد')),
                ('departure_date', models.DateField(verbose_name='تاریخ حرکت')),
                ('return_date', models.DateField(verbose_name='تاریخ برگشت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('adult_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت بزرگسال')),
                ('child_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت کودک')),
                ('services', models.TextField(blank=True, null=True, verbose_name='خدمات تور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'در حال ثبت نام'), ('full', 'تکمیل ظرفیت'), ('running', 'در حال اجرا'), ('finished', 'پایان یافته'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
