# Generated by Django 5.2.15 on 2026-09-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hotel', 'هتل'), ('eco_lodge', 'بوم\u200cگردی'), ('villa', 'ویلا'), ('suite', 'سوئیت'), ('hostel', 'هاستل'), ('camp', 'کمپ'), ('local_house', 'خانه محلی'), ('other', 'سایر')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tours.country'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('flight', 'پرواز'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('transfer', 'ترانسفر')], default='flight', max_length=20)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_from', to='tours.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_to', to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تور')),
                ('tour_code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='کد تور')),
                ('destination', models.CharField(max_length=100, verbose_name='مقصد')),
                ('departure_date', models.DateField(verbose_name='تاریخ حرکت')),
                ('return_date', models.DateField(verbose_name='تاریخ برگشت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('adult_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت بزرگسال')),
                ('child_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت کودک')),
                ('services', models.TextField(blank=True, null=True, verbose_name='خدمات تور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('open', 'در حال ثبت نام'), ('full', 'تکمیل ظرفیت'), ('running', 'در حال اجرا'), ('finished', 'پایان یافته'), ('cancelled', 'لغو شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='TourAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.accommodation')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.flight')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=100)),
                ('processing_days', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.country')),
            ],
        ),
    ]
