# Generated by Django 5.2.15 on 2026-06-08 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_city_country_tour_destination_city_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hotel', 'هتل'), ('eco_lodge', 'بوم\u200cگردی'), ('villa', 'ویلا'), ('suite', 'سوئیت'), ('hostel', 'هاستل'), ('camp', 'کمپ'), ('local_house', 'خانه محلی'), ('other', 'سایر')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.city')),
            ],
        ),
    ]
