# Generated by Django 5.2.15 on 2026-06-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.accommodation')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='tours.tour')),
            ],
        ),
    ]
