# Generated by Django 5.2.15 on 2026-06-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_touraccommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('flight', 'پرواز'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('transfer', 'ترانسفر')], default='flight', max_length=20)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_from', to='tours.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights_to', to='tours.city')),
            ],
        ),
        migrations.CreateModel(
            name='TourFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.flight')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='tours.tour')),
            ],
        ),
    ]
