# Generated by Django 5.2.15 on 2026-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
