# Generated by Django 5.2.15 on 2026-06-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0002_alter_passenger_customer_code'),
        ('tours', '0005_flight_tourflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('finished', 'پایان یافته')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='passengers.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('tour', 'تور'), ('flight', 'پرواز'), ('accommodation', 'اقامتگاه'), ('visa', 'ویزا')], max_length=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.accommodation')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.flight')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tour')),
            ],
        ),
    ]
