# Generated by Django 5.2.15 on 2026-06-14 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('tours', '0006_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.visa'),
        ),
    ]
