# Generated by Django 5.2.15 on 2026-06-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingitem_visa'),
        ('tours', '0007_visa_validity_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='bookings.booking')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.visa')),
            ],
        ),
    ]
