# Generated by Django 5.2.15 on 2026-06-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingvisa'),
        ('tours', '0007_visa_validity_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('nights', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.accommodation')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='bookings.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.flight')),
            ],
        ),
    ]
